name: 'Check latest version'
description: 'GitHub action to retrieve the latest version of a package in various package managers'
author: 'Michele Mancioppi'
inputs:
  package-manager:
    required: true
    description: 'The package manager hosting the package; currently supported values are "npm" and "pypi"'
    default: 'npm'
  package-name:
    required: true
    description: 'The name of the package to be checked, e.g., "@lumigo/opentelemetry"'
runs:
  using: 'node16'
  main: 'dist/index.js'
